<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\IAssessmentTrusteeIndicatorBiz.cs" />
    <Compile Remove="Contracts\IAssessmentTrusteeUserBiz.cs" />
    <Compile Remove="Contracts\IExpertiseBiz.cs" />
    <Compile Remove="Contracts\IExpertiseIndicatorBiz.cs" />
    <Compile Remove="Contracts\IGradeBiz.cs" />
    <Compile Remove="Contracts\IIndicatorBiz.cs" />
    <Compile Remove="Contracts\IMonthBiz.cs" />
    <Compile Remove="Contracts\IMonthUserCommissionBiz.cs" />
    <Compile Remove="Contracts\IMonthUserIndicatorBiz.cs" />
    <Compile Remove="Contracts\IReportBiz.cs" />
    <Compile Remove="Contracts\IUnitDivisionBiz.cs" />
    <Compile Remove="Contracts\IUnitDivisionIndicatorBiz.cs" />
    <Compile Remove="Contracts\IUnitDivisionUserBiz.cs" />
    <Compile Remove="Contracts\IUserExpertiseBiz.cs" />
    <Compile Remove="Contracts\IUserRoleBiz.cs" />
    <Compile Remove="Modules\AssessmentTrusteeBiz.cs" />
    <Compile Remove="Modules\AssessmentTrusteeIndicatorBiz.cs" />
    <Compile Remove="Modules\AssessmentTrusteeUserBiz.cs" />
    <Compile Remove="Modules\ExpertiseBiz.cs" />
    <Compile Remove="Modules\ExpertiseIndicatorBiz.cs" />
    <Compile Remove="Modules\GradeBiz.cs" />
    <Compile Remove="Modules\IndicatorBiz.cs" />
    <Compile Remove="Modules\MonthBiz.cs" />
    <Compile Remove="Modules\MonthUserCommissionBiz.cs" />
    <Compile Remove="Modules\MonthUserIndicatorBiz.cs" />
    <Compile Remove="Modules\ReportBiz.cs" />
    <Compile Remove="Modules\UnitDivisionBiz.cs" />
    <Compile Remove="Modules\UnitDivisionIndicatorBiz.cs" />
    <Compile Remove="Modules\UnitDivisionUserBiz.cs" />
    <Compile Remove="Modules\UserExpertiseBiz.cs" />
    <Compile Remove="Modules\UserRoleBiz.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper.Oracle.NetCore" Version="1.0.1" />
    <PackageReference Include="morelinq" Version="3.3.2" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Eydi.Common\ES.Common.csproj" />
    <ProjectReference Include="..\Eydi.Core\ES.Core.csproj" />
    <ProjectReference Include="..\Eydi.Domain\ES.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GemBox.Document">
      <HintPath>C:\Program Files (x86)\GemBox Software\GemBox.Document 2.9\Bin\net35\GemBox.Document.dll</HintPath>
    </Reference>
    <Reference Include="GemBox.Pdf">
      <HintPath>C:\Program Files (x86)\GemBox Software\GemBox.Pdf 1.3\Bin\net35\GemBox.Pdf.dll</HintPath>
    </Reference>
    <Reference Include="GemBox.Spreadsheet">
      <HintPath>C:\Program Files (x86)\GemBox Software\GemBox.Spreadsheet 4.3\Bin\net35\GemBox.Spreadsheet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\common\" />
  </ItemGroup>

</Project>
