<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ES.Common\ES.Common.csproj" />
    <ProjectReference Include="..\ES.Core\ES.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
  </ItemGroup>

</Project>
